# Generated by Django 3.2.9 on 2021-11-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='data',
            new_name='date',
        ),
    ]
